config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  resources :books, only: [:index, :new, :create] do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  def self.search(keyword)
    return Book.all unless keyword
    Book.where('title LIKE(?) OR author LIKE(?)', "%#{keyword}%", "%#{keyword}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end
  def new
    @book = Book.new
  end
  def create
    Book.create(book_params)
  end
  def search
    @books = Book.search(params[:keyword])
  end

  private
    def book_params
      params.require(:book).permit(:title, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/create.html.erb
<p>登録完了</p>
<a href="/books">戻る</a>

app/views/books/index.html.erb
<a href="/books/new">本の登録</a>
<a href="/books/search">本の検索</a>

app/views/books/new.html.erb
<%= form_with(model: @book, local: true) do |f| %>
  <%= f.text_field :title, placeholder: "Title" %>
  <%= f.text_field :author, placeholder: "Author" %>
  <%= f.submit "send" %>
<% end %>
  

app/views/books/search.html.erb
<%= form_with(url: search_books_path, local: true, method: :get) do |f| %>
  <%= f.text_field :keyword, placeholder: 'keyword' %>
  <%= f.submit "検索" %>
<% end %>
<p><%= @books.length %>件の本が見つかりました</p>
<p>----------------------</p>
<% @books.each do |book| %>
  <p>タイトル: <%= book.title %></p>
  <p>著者: <%= book.author %></p>
  <p>----------------------</p>
<% end %>
<a href="/books">戻る</a> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchBooks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>